### ISSUE TITLE
Add a CI to format the backend

### ISSUE THREAD

**Issue by clarani** [XavB64/lowtrip#61]
# Description
Add a github job to format and lint the backend. Use black (and flake8 ?)

**Comment by mikaelarguedas** [comment]
Nice coincidence I opened https://github.com/XavB64/lowtrip/pull/56 that same day.

- ruff format does only the formatting (equivalent to black)
- ruff check does the linting (flake8 + many other things)

It has the advantage of being much faster (rust-based) and feature complete than flake8.

If you like the idea I can add CI to it and make a separate PR for adding the linter part

**Comment by XavB64** [comment]
Can we close this issue now as ruff has been installed ?

**Comment by clarani** [comment]
Yes this issue can be closed, see https://github.com/XavB64/lowtrip/pull/69
