### ISSUE TITLE
Use ADEME API for updated co2e values

### ISSUE THREAD

**Issue by tomasbastien** [XavB64/lowtrip#74]
Hello there !

ADEME org now provides API to query multiples entries from their database, including km to co2e conversion. You can freely ask for an API key (Bearer Auth) to use it at [impactco2@ademe.fr](mailto:impactco2@ademe.fr), more details on : [https://impactco2.fr/api-doc](https://impactco2.fr/api-doc)

It could replace local values that are actually used in this tool.

_I've been working on a similar tool on my side, hightly motivated by volonteering for POW France (available on [https://protectourwinters.fr/outil-co2e/](https://protectourwinters.fr/outil-co2e/) and code on [https://github.com/tomasbastien/co2e-calculator](https://github.com/tomasbastien/co2e-calculator)), I'll be sharing common concerns that I encountered in separated issues in this repo_

**Comment by XavB64** [comment]
Hello!

The emission factor values are stored in the parameters.py file and these values don't usually change very often, so we don't think it would be necessary to use another API to get it. 

Also, you'll find that some values are different from the ones used in ADEME, notably for trains and electric vehicles as we account for country-specific emission factors ;)

I will close the issue for now, but thanks for sharing this tool with us ! 👍
