### ISSUE TITLE
Stick as much as possible to roads and tracks

### ISSUE THREAD

**Issue by tomasbastien** [XavB64/lowtrip#76]
Hello there !

No sure if it's a major concern, but it looks like paths are optimized to lower total of segments (reduce computing time ?). It could result on imprecision on the kilometers total used in the co2e calculation.

_I've been working on a similar tool on my side, hightly motivated by volonteering for POW France (available on https://protectourwinters.fr/outil-co2e/ and code on https://github.com/tomasbastien/co2e-calculator), I'll be sharing common concerns that I encountered in separated issues in this repo_

**Comment by XavB64** [comment]
Hello !

Yes indeed, retrieving the whole geometry from the API takes ~2x longer than the simplified ones, we chose for now to use the simplified geometries (does not change too much visually on a long trip).

However, we still get the real total distance from the API request, therefore we made sure to use this value to compute the emissions: there is no underestimation in the computation !

Thank you for sharing your project, I will have a look soon :)
